#!/bin/bash

# If $HOME/.local/bin does not exist, make one
test ! -d "$HOME/.local/bin" && mkdir -p "$HOME/.local/bin"

# Custom PATH: if $HOME/.local/bin is not present in $PATH, include it
test -z "$(echo $PATH|grep "$HOME/\.local/bin")" && PATH="$HOME/.local/bin:$PATH"

# xadf variable declarations
declare -x xadfconfig="$HOME/.config/xadf"
declare -x xadfmods="$HOME/.local/xadf"
declare -x xadfdir="XADFDIR"

# Load base functions
. $xadfmods/initrc

# Check whether recipe.txt exists, if it doesn't, generate one
test ! -f "$xadfconfig/recipe.txt" && xadf --build-recipe

# Load modules (reloads if already present)
unset xadfmod_list && xadfmod "$xadfconfig/recipe.txt"

# Only run this block in a bash shell
if test -n "$BASH_VERSION" ; then
  # Sources $xadfconfig/bashrc if exist, otherwise sources $xadfmods/bashrc
  test -f "$xadfconfig/bashrc" && source "$xadfconfig/bashrc" || source "$xadfmods/bashrc"
fi

# Only run this block in a zsh shell
if test -n "$ZSH_VERSION" ; then
  # Sources $xadfconfig/zshrc if exist, otherwise sources $xadfmods/zshrc
  test -f "$xadfconfig/zshrc" && source "$xadfconfig/zshrc" || source "$xadfmods/zshrc"
fi

