#!/bin/bash

########################################################################
## Some extras
########################################################################

## This function makes qr code of text $2, then it
## displays the resulting qrcode.
function qrquick
{
  if [ $# -eq 2 ]; then
    qrencode -s 12 -m 1 -o $1.png "$2";
    display $1.png
  else
    echo "usage: qrquick <output> <text>"
  fi
}

## Specific functions to get user agents from our server

uaput(){
case $1 in
"")
  target=ytua
  ;;
*)
  target=$1
  ;;
esac

ftp ftp.xenomancy.id <<EOF
cd xenoagents/agents
put $target
bye
EOF
}

uaget(){
case $1 in
"")
  target=ytua
  ;;
*)
  target=$1
  ;;
esac

ftp ftp.xenomancy.id <<EOF
cd xenoagents/agents
get $target
bye
EOF
}
