#!/bin/zsh
###############################################################################
#
#   xadf - zshrc
#   Copyright (C) 2023  Hendrik Lie
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#   Author: Hendrik Lie
#   Email : <hendriklie72@gmail.com>
#
###############################################################################
#
# SUMMARY
# Loaded from $xadfconfig/xadfrc. Should contain a sane default configuration.
# The basic skeleton is derived from the original code block for custom zsh
# function and alias definitions.

# Check whether zsh_aliases and zsh_functions in $xadfmods exist
test ! -f "$xadfmods/zsh_aliases"   && cp "$xadfmods/templates/zsh_aliases"   "$xadfmods/zsh_aliases"
test ! -f "$xadfmods/zsh_functions" && cp "$xadfmods/templates/zsh_functions" "$xadfmods/zsh_functions"

# Sources ~/.zshrc.d if exist
test -d "$HOME/.zshrc.d" && src "$HOME/.zshrc.d"
